### ISSUE TITLE
5.6 incompatibilities

### ISSUE THREAD

**Issue by JABirchall** [Setasign/php-stub-generator#3]
I need to generate stubs for an application that was encoded with ioncube for 5.6, and since ioncube is a snowflake, ioncube 7.1 cant load files encoded files for 5.6 and your library doesnt support 5.6. Could it be possible to allow this backwards compatibility.

**Comment by JanSlabon** [comment]
Just pass the files to the stub generator before it is encoded with ioncube. That's how we do it...
Support for 5.6 could work but we will definitely not do it. @Bob4ever I guess I'm right?

**Comment by MaximilianKresse** [comment]
Like @JanSlabon said, you have to pass the unencoded files to the stub generator.
At the moment the stub generator can only generate stubs from pure unencoded php files. The application doesn't need to be compatible with php 7.1.
https://github.com/goaop/parser-reflection only have to be able to read the code.
