### ISSUE TITLE
Trait problem resolved

### ISSUE THREAD

**Issue by szepeviktor** [Setasign/php-stub-generator#4]
Just now!
https://github.com/php/php-src/commit/53efa1b0c69b463ea9d3606d828c036129f2dec9
Actually in March.

**Comment by MaximilianKresse** [comment]
Oh nice :-) But if I see this correctly this bugfix was only done for the php 8.0 branch (https://3v4l.org/mrA8M). So it will take some time until we can use it. I'll take a look into it when php8 is released and the [goaop/parser-reflection](https://github.com/goaop/parser-reflection) works in php8.
